[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = '0.8.17'
optimizer = true
optimizer_runs = 50
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
